### ISSUE TITLE
[DivByZeroDefect] on i386 (Windows 11)

### ISSUE THREAD

**Issue by SecDbg** [treeform/puppy#121]
I'm not sure whether this would be better suited for the puppy issues or for zippy issues, but I'll just leave it here and hope someone can offer some advice.

I'm trying to use puppy in an x86 compiled program, with this basic Nim code
`echo fetch("http://neverssl.com/")`

I'm compiling it with the following command:
` nim --cpu:i386 --gcc.path=C:\mingw32\bin c -r .\main.nim`

I haven't really done much messing around with settings since I'm not particularly sure what might help
I've looked at zippy issues, but saw no issues regarding this error, so I'm not sure if this is an error in puppy's usage of zippy, or an issue with zippy itself.

Output:

```
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
57808 lines; 2.002s; 91.305MiB peakmem; proj: D:\Testing-Puppy-86\main.nim; out: D:\Testing-Puppy-86\main.exe [SuccessX]
Hint: D:\Testing-Puppy-86\main.exe [Exec]
D:\Testing-Puppy-86\main.nim(3) main
C:\Users\Admin\.nimble\pkgs2\puppy-2.1.2-9d583654c5ce17fd0223da5102e5e9b01fba74fa\puppy.nim(108) fetch
C:\Users\Admin\.nimble\pkgs2\puppy-2.1.2-9d583654c5ce17fd0223da5102e5e9b01fba74fa\puppy.nim(57) get
C:\Users\Admin\.nimble\pkgs2\puppy-2.1.2-9d583654c5ce17fd0223da5102e5e9b01fba74fa\puppy.nim(37) fetch
C:\Users\Admin\.nimble\pkgs2\puppy-2.1.2-9d583654c5ce17fd0223da5102e5e9b01fba74fa\puppy\platforms\win32\platform.nim(289) internalFetch
C:\Users\Admin\.nimble\pkgs2\zippy-0.10.15-9bafc21499496c48765fd4abb0930e446b0d4f60\zippy.nim(171) uncompress
C:\Users\Admin\.nimble\pkgs2\zippy-0.10.15-9bafc21499496c48765fd4abb0930e446b0d4f60\zippy.nim(128) uncompress
C:\Users\Admin\.nimble\pkgs2\zippy-0.10.15-9bafc21499496c48765fd4abb0930e446b0d4f60\zippy\gzip.nim(76) uncompressGzip
C:\Users\Admin\.choosenim\toolchains\nim-2.2.0\lib\system\fatal.nim(53) sysFatal
Error: unhandled exception: division by zero [DivByZeroDefect]
Error: execution of an external program failed: 'D:\Testing-Puppy-86\main.exe'
```

**Comment by guzba** [comment]
I believe the issue here is in Zippy, where I do `dst.len mod (1 shl 32)` which will not work on 32 bit.

I don't have or ever use 32 bit stuff so I've never really thought much about it, I'm always a bit surprised when it comes up. Is this for a some old hardware or is there a good 32 bit motivator these days I could keep in mind?

**Comment by SecDbg** [comment]
There's not really much of a use nowadays, I just like making my programs more compatible with older hardware and also reducing binary size. A lot of my work is offensive (maldev) oriented so helps to have it run on a wide range of systems likewise.

I don't know much myself about lower level stuff, but would this be an easy fix by just changing the value, or would there be more to it? I haven't looked at it much myself so not very sure.

**Comment by guzba** [comment]
I don't want to pretend my libs are tested and actually support 32 bit, there's no fun in that and it'll never matter to me. It is not as simple as just fixing this one thing.

The fix here is for me to add a build flag to Puppy, something like `-d:puppyNoZippy` to optionally remove Zippy from Puppy. You can then use Zlib or something like that to do the gzip uncompressing since that is build to support 32 bit.

Alternatively you could fork Puppy and just remove the Zippy stuff quick.

**Comment by SecDbg** [comment]
Yeah fair enough, x86 isn't particularly popular nowadays so no real need to test for it.

I'll look into either forking it and implementing changes or into the Winim library, which seems to have some abstractions that I can use for this

Thanks for the support
