### ISSUE TITLE
Install error on Termux

### ISSUE THREAD

**Issue by doongjohn** [treeform/puppy#8]
![20210404_155325](https://user-images.githubusercontent.com/40219740/113501111-08152500-955e-11eb-97e7-2a3c04a8ff9b.jpg)

maybe android is not supported?

**Comment by treeform** [comment]
Sorry at the moment Android and iOS are not supported. The reason is that they don't ship libcurl by default. To stay with the spirit of puppy I think its bet to go through the Java NDK api on android and swift/objective-c API on iOS to make ssl requests. This is currently not implemented. I don't have plans on making this work, but PRs welcome.

Termux is doubly wearied as its not real android and not real linux. For termux is probably best to install libcurl? I don't know.
