### ISSUE TITLE
Support for response body streaming

### ISSUE THREAD

**Issue by its5Q** [treeform/puppy#95]
Currently, if you want to retrieve a large page, you have to load it all into memory. Because of that, you can't download big files. So, it would be nice if there was a way to stream the response, so we could read it by chunks manually.
Meanwhile, I've made a [fork](https://github.com/its5Q/puppy) for myself that allows streaming, but the code is not ideal and it's only for windows. It would be great if something like that would be properly implemented in puppy.

**Comment by treeform** [comment]
We apologize, but we are not planning on implementing streaming capabilities at this time due to the complexity of getting it right with the various APIs and platforms. We just don't like streaming for various reasons. I want to look into HTTP range requests, as they may be a better option for large file transfers. In the meantime, please feel free to use your fork of the project if it meets your needs.

**Comment by its5Q** [comment]
> We apologize, but we are not planning on implementing streaming capabilities at this time due to the complexity of getting it right with the various APIs and platforms. We just don't like streaming for various reasons. I want to look into HTTP range requests, as they may be a better option for large file transfers. In the meantime, please feel free to use your fork of the project if it meets your needs.

No worries, thank you, I will use my fork then.
